### ISSUE TITLE
Replicate the repo

### ISSUE THREAD

**Issue by sauravsolanki** [CHamilton0/Space-Analytics-Engine#1]
Hi @CHamilton0 , I am working on pruning the Matterport MaskRCNN Model. I am not able to Prune the Model due to error:

```
"/home/<>/envs/env-name/lib/python3.6/site-packages/tensorflow/python/keras/engine/functional.py", line 1162, in process_node
    output_tensors = layer(input_tensors, **kwargs)
UnboundLocalError: local variable 'kwargs' referenced before assignment
```

Can you please share 
1. the conda environment env.yml or requirement.txt with exact python version
2.  Trained Model so that I can see pruning on my end.
3. or any changes in TF source code. 

This would be great help to me and community. Thanks you.

You can contact me at : sausol.solanki@gmail.com

**Comment by CHamilton0** [comment]
Hi @sauravsolanki,

1. I have uploaded the env.yml file as requested.
2.  Please also see release v1.1 for the trained weights file. This can be used by loading the weights in the testing or pruning notebooks. 
3. I did not make any changes to the TF source code.

Let me know how it goes.

**Comment by sauravsolanki** [comment]
@CHamilton0 Thank you. It helped me a lot. Now I know reasons behind why I could not able to  prune. I would be happy if you can answer my query:
1. Why you did not use BatchNorm? I am trying to clone model with batchnorm but seems model hasn't been cloned properly. I am facing issue while attaching add_loss().

Thank you @CHamilton0 , you saved my many days of googling and diving in issues.

**Comment by CHamilton0** [comment]
Hi @sauravsolanki,

I'm glad I was able to help so far.
I did not use BatchNorm because of some issues I faced when loading and saving the model. I believe that there is a difference between the BatchNorm layer used in the Mask R-CNN implementation and the normal BatchNorm layer in keras.

Hopefully this helps.
